steps:
- name: 'gcr.io/cloud-builders/gcloud' # Using the official GCloud builder, which reliably includes bash
  args: ['bash', 'build.sh'] # Now we tell the GCloud container to execute 'bash build.sh'
  # This step runs your shell script

# This logging option fixes the previous "Failed to trigger build" error
options:
  logging: CLOUD_LOGGING_ONLY

# Uncomment the sections below when you are ready to use them.

# --- Optional: Build and push a Docker image to Artifact Registry ---
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:latest', '.']
#   id: 'Build Image'

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:latest']
#   id: 'Push Image'

# --- Optional: Define artifacts for files you want to save after the build ---
# artifacts:
#   objects:
#     location: 'gs://your-artifacts-bucket-name'
#     paths: ['build_output/info.txt']
