steps:
- name: 'gcr.io/cloud-builders/bash' # Using the official bash builder (should work now)
  # Force the container to use /bin/bash as the command interpreter
  entrypoint: '/bin/bash'
  # Pass the script name as the argument to the interpreter
  args: ['build.sh']
  id: 'Run Shell Script'

# This logging option fixes the previous "Failed to trigger build" error
options:
  logging: CLOUD_LOGGING_ONLY

# Uncomment the sections below when you are ready to use them.

# --- Optional: Build and push a Docker image to Artifact Registry ---
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:latest', '.']
#   id: 'Build Image'

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:latest']
#   id: 'Push Image'

# --- Optional: Define artifacts for files you want to save after the build ---
# artifacts:
#   objects:
#     location: 'gs://your-artifacts-bucket-name'
#     paths: ['build_output/info.txt']
