# The steps define the sequential actions Cloud Build will take.

steps:
# Step 1: Set the build.sh file as executable
# Cloud Build workspace files are not executable by default, so we must add permissions.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'chmod +x ./build.sh']
  id: 'Set-Executable-Permission'

# Step 2: Execute the custom build script
# We use the official Cloud Build bash builder image to run our shell script.
- name: 'gcr.io/cloud-builders/bash'
  args: ['./build.sh']
  id: 'Execute-Custom-Script'

# Step 3 (Example): Build and push a Docker image 
# If you were building a container, it would look like this:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA', '.']
#   id: 'Build-Docker-Image'

# The images field tells Cloud Build to automatically push the tagged image to Artifact Registry/GCR
# images:
# - 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA'

# Optional: Configuration for storing build artifacts in Cloud Storage
# artifacts:
#   objects:
#     location: 'gs://your-artifact-bucket-name/' # IMPORTANT: Replace this with your bucket name
#     paths: ['build_output/info.txt'] # Path to the file created in build.sh

timeout: '1200s' # Set a maximum timeout of 20 minutes for the entire build
