steps:
# Step 1: Run the 'hello.sh' script.
# We use the 'gcr.io/cloud-builders/gcloud' image because it is Google's most
# reliable official builder and guarantees a stable bash environment (/bin/bash)
# is available, which solves the previous "No such file or directory" error.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['build.sh']
  id: 'Run Hello World Scripttesing'

# Options: This section fixes the "Failed to trigger build" error
# related to custom service accounts and log permissions.
options:
  logging: CLOUD_LOGGING_ONLY
